Break the list
Description
Write a Python program to divide a given list into chunks of size k.

The number of elements in the list need not to be divisible by k.
For example, if you want to divide the list [1,2,3,4,5,6,7] into chunk size k=4, then the first chunk will be [1,2,3,4] and the second one will have [5,6,7]. i.e. the last chunk need not have k elements.
The input will have two lines, the first line would have the list and the second line would have the value of k.(the code for taking input has already been written, you should not change that)
The final output should have the list chunks in different lines.

Sample Input:
[1,2,3,4,5,6,7,8,9]
3
Sample Output:

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [3]:
input_list=[[1,2,3,4,5,6,7,8,9],3]
lis=input_list[0]
k=input_list[1]

In [22]:
k

3

In [26]:
[lis[x:x+k] for x in range(0, len(lis), k)]
for i in sublists:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [1]:
input_list=[[1,2,3,4,5,6,7,8,9],3]
lis=input_list[0]
k=input_list[1]
for i in range(0, len(lis), k):  
    print(lis[i:i + k]) 

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


Scrabble
Description
Assume that you are trying to complete a crossword puzzle. In a crossword puzzle, some letters are given and you have to figure out which complete word can you make out of it.
For example, given letters "cwd"in the same order, you can make the word  "crossword" or "crowd" with it. But if "dw" is given in that order, you cannot make "crossword" out of it because d and w are in the opposite order here.

You want to find an efficient method and write a code for this process. 
The code will take two strings as input in two lines. The first string will contain letters on the crossword("cwd"), and the second string will contain a word that you want to check.(i.e. you want to check whether the word can be made out of given letters in the same order).
The output should say "yes" if the word can be formed, else it should say "no"
Sample Input 1:
ccwd
crossword
Sample Output1:
no

Sample Input 2:
cwd
crossword
Sample Output 2:
yes

Note: Using regex is also one of the ways of solving this problem. You can read more about regex(regular expressions) here. Although, you can simply use loops and conditionals too to solve the problem.
Execution Time Limit
15 seconds

for checking a substring : example----

In [40]:
import re
a = "I believe that the biggest castle in the world is Prague Castle "
b = r'\b' + r'\b.*\b'.join(re.escape(word) for word in "the bigst castle".split(' ')) + r'\b'
bool(re.search(b, a))

False

In [57]:
letters=input()#letters already in the crossword
guess=input()#word to check for fit
letters = '.*'.join(list(letters))
if bool(re.search(letters, guess)):
    print("Yes")
else:
    print("No")

 sor
 cross


No


In [58]:
#alternate solution
letters=input()#letters already in the crossword
guess=input()#word to check for fit
i = 0
for w in guess:
    if w == letters[i]: 
        i += 1
        if i >= len(letters): break

if (i == len(letters)):
    print('yes')
else:
    print('no')
    

 crw
 crossword


yes


In [ ]:
### Paying the rent
Description
You are moving to a new city for an internship for a few months and have to rent a house for that purpose.
You have to pay the full month's house rent even if you have lived for a few days for that month. i.e. 
if you start on 15th Jan and leave by 15th May, you still have to pay full rent for months of Jan and May too.

Your task is to find the months that you have to pay rent for so that you can write post-dated cheques to your landlord.

You will be given two dates as input and your task is to print all months between the dates including the months the dates are from.
The input will contain the two dates in a list as follows:
[2017,1,1,2017,3,4] which corresponds to 1st Jan, 2017 and 4th March, 2017. This date is in the format(yyyy,mm,dd)
(the code for taking input has already been written for you, please don't modify that)
The output should contain a list with names of months you have to pay the rent for(the list should be sorted chronologically  based on months, i.e May should come before August). You can assume that there won't be more than 12 months between two dates.
You'll need to use the datetime module for this problem which can be referred to here. You can choose to use any other method too.

Sample Input:
[2017,1,1,2017,1,1]
Sample Output:
['January']


In [10]:
import datetime
from datetime import date
input_list=[2017,8,1,2018,2,1]
dateStart=datetime.date(input_list[0],input_list[1],input_list[2])
dateEnd=datetime.date(input_list[3],input_list[4],input_list[5])
print(dateStart,"\n",dateEnd)

2017-08-01 
 2018-02-01


In [114]:
diff=dateStart - dateEnd
diff.days

-184

In [115]:

dateStart.month


8

In [12]:
import calendar
calendar.month_name[dateStart.month]

'August'

In [117]:
if dateStart.month==dateEnd.month:
    print([calendar.month_name[dateStart.month]])

In [13]:
import pandas as pd
dates=pd.date_range(dateStart, dateEnd+ pd.offsets.MonthEnd(),freq="M", closed=None)
dates

DatetimeIndex(['2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30',
               '2017-12-31', '2018-01-31', '2018-02-28'],
              dtype='datetime64[ns]', freq='M')

In [125]:
l=[]
for month_idx in dates.month:
    l.append(calendar.month_name[month_idx])
print (l)
   

['August', 'September', 'October', 'November', 'December', 'January', 'February']


In [2]:
import datetime
from datetime import date
input_list=[2017,8,1,2018,2,1]
dateStart=datetime.date(input_list[0],input_list[1],input_list[2])
dateEnd=datetime.date(input_list[3],input_list[4],input_list[5])
print(dateStart,"\n",dateEnd)
import calendar
calendar.month_name[dateStart.month]
import pandas as pd
dates=pd.date_range(dateStart, dateEnd+ pd.offsets.MonthEnd(),freq="M", closed=None)
l=[]
for month_idx in dates.month:
    l.append(month_idx)
n=[]
for i in sorted(l):
    n.append(calendar.month_name[i])
print (n)
    
   

2017-08-01 
 2018-02-01
['January', 'February', 'August', 'September', 'October', 'November', 'December']


In [42]:
def calculate_monthdelta(date1, date2):
    print(abs(date1.year - date2.year) * 12 + abs(date1.month - date2.month))

In [43]:
calculate_monthdelta(dateStart,dateEnd)

18


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,
        8], dtype=int64)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,
        8], dtype=int64)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,
        8], dtype=int64)

In [33]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
while dateStart < dateEnd:
    print(dateStart)
    dateStart += relativedelta(months=1)

2017-03-01
2017-04-01
2017-05-01
2017-06-01
2017-07-01
2017-08-01
2017-09-01
2017-10-01
2017-11-01
2017-12-01
2018-01-01
2018-02-01
2018-03-01
2018-04-01
2018-05-01
2018-06-01
2018-07-01
2018-08-01
2018-09-01


### remove empty lists from the list

In [141]:
list1=[1,2,3,[1,2],[],[1,2],"x",["1"],[]," ",1]

In [142]:
list2 = filter(None, list1)
list2

In [143]:
list2 = []
for item in list1:
    if item!=[]:
        list2.append(item)
print(list2)

[1, 2, 3, [1, 2], [1, 2], 'x', ['1'], ' ', 1]


In [144]:
print([e for e in list1 if e])

[1, 2, 3, [1, 2], [1, 2], 'x', ['1'], ' ', 1]


In [146]:
print([e for e in list1 if e!=[]])

[1, 2, 3, [1, 2], [1, 2], 'x', ['1'], ' ', 1]


Q-2 Description
You are provided with the community and crime dataset. 

Your task is to print the number of rows and name of columns. Assign the number of rows to a new variable named 'n_row' and the number of columns to a variable named 'n_column'.

The dataset can be found at 'https://media-doselect.s3.amazonaws.com/generic/ka2eL88aayAyB3W7eRVL1xWq/communities_final.csv'. 

In [1]:
Q-2 Description
You are provided with the community and crime dataset. 

Your task is to print the number of rows and name of columns. Assign the number of rows to a new variable named 'n_row' and the number of columns to a variable named 'n_column'.

The dataset can be found at 'https://media-doselect.s3.amazonaws.com/generic/ka2eL88aayAyB3W7eRVL1xWq/communities_final.csv'. 


import numpy as np
import pandas as pd

# Read training data
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/ka2eL88aayAyB3W7eRVL1xWq/communities_final.csv')

# Assign number of rows to a new variable
n_row = df.shape[0]

# Assign number of columns to a new variable
n_column = df.shape[1]

print(n_row)
print(n_column)

1994
128


In [2]:
df.shape

(1994, 128)